name: CI/CD Pipeline

on:
  push:
    branches:
      - development

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Eslint
        run: npm run lint
      - name: Prettier
        run: npm run format
      - name: Test
        run: npm run test
