name: CI/CD Pipeline

on:
  push:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: '20'

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build

      - name: Deploy to server
        run: |
          sshpass -p 'O5izCcjbB49oqukh' ssh -o StrictHostKeyChecking=no root@185.8.172.52 '
            cd /root/nest-ci-cd &&
            sudo apt update &&
            sudo apt install -y nodejs npm &&
            git pull &&
            sudo npm install -g pm2 &&
            pm2 stop nest-ci-cd &&
            pm2 delete nest-ci-cd &&
            pm2 start /dist/main.js --name nest-ci-cd
          '
